### ISSUE TITLE
Remove y-axis in circular mahattan plot

### ISSUE THREAD

**Issue by GuoanQi1996** [YinLiLin/CMplot#101]
Greetings!
Is there any way to remove the y-axis in circular manhattan plot? Thanks.

**Comment by YinLiLin** [comment]
Yes, please add the parameter 'cir.axis=FALSE' to have try.

**Comment by GuoanQi1996** [comment]
Appreciate your quick response! It works after adding parameter 'cir.axis=FALSE' to remove the y-axis. And I got another issue,I want to reduce the label size of x-axis as they are overlapped now, I set the parameter "lab.cex" and "axis.cex", but the output figure has the same font size as before. Anything wrong?

**Comment by GuoanQi1996** [comment]
Hey YinLi, I have solved the problem after look into the source codes.
"lab.cex" is exactly the parameter control the font size of label, and it is called at line 1082 and 1087 for circular mahattan plot in source codes.
`text(ticks1[t],ticks2[t],chr.labels[t],srt=angle,font=lab.font,cex=lab.cex-0.5, adj=c(0.5, 0))`
As we can see the `cex` is set to `lab.cex-0.5` which means the parameter `lab.cex` must set bigger than 0.5 otherwise a negative value would always lead it to the defaulted setting, and therefore give a same plot.
