### ISSUE TITLE
Chromosome label error

### ISSUE THREAD

**Issue by cfz1998** [YinLiLin/CMplot#106]
Hi! @YinLiLin 

I could not find my chr12 label in the CMplot output.

![Rect_Manhtn Boscalid gwas  5](https://github.com/YinLiLin/CMplot/assets/60096719/e9407571-5588-465f-9cb5-09c2c9f4d0c5)

How do you think I could fix it?

**Comment by YinLiLin** [comment]
This is because the labels are too crowded, please try to specify an rotation angle to the argument "chr.labels.angle", e.g., CMplot(..., chr.labels.angle=45).

**Comment by cfz1998** [comment]
> This is because the labels are too crowded, please try to specify an rotation angle to the argument "chr.labels.angle", e.g., CMplot(..., chr.labels.angle=45).

Hi! It works.
Thanks!
