### ISSUE TITLE
hightlight is not working for multi-traits rectangle manhattan plot

### ISSUE THREAD

**Issue by GuoanQi1996** [YinLiLin/CMplot#130]
Hi, YinLi. 
Thank you for developing this wonderful function.

I am currently working with SNP and Indel GWAS results and i want to plot them via multi-traits mode in cmplot, in which case the two types of variants could be displayed in different point shapes and colors. I organized my data to:
 
Variants Name | CHR | POS | SNP-P | Indel-P |
| --- | --- | --- | --- | --- | 
SNP1 | 1 | 1000 | 1e-5 | NA |
SNP2 | 1 | 10000 | 0.99 | NA |
... | ... | ... | ... | ... |
Indel1 | 1 | 1050 | NA | 1e-5 |
Indel2 | 1 | 10050 | NA | 0.85 |

And here is my code,
``CMplot(my_data, plot.type="m", multraits=TRUE,cex = c(1,1.2), col = c("#5DB1DD","#FFC20A"),
LOG10=TRUE, threshold=c(1e-5),axis.cex = 1.3,legend.cex = 1.3,
threshold.lty=2, threshold.lwd=1, threshold.col="darkblue", amplify=F,pch = c(16,17),
chr.den.col=NULL, points.alpha = 150,chr.labels.angle = 45,
file="jpg",file.name="test1",dpi=300,file.output=TRUE,highlight = 'Indel2',verbose=TRUE,width=16,height=3,highlight.col = 'red',highlight.text = 'Indel2')``

However, the Indel2 is not highlighted red. Could you please assist me in this issue? 
Appreciated!

**Comment by YinLiLin** [comment]
Sorry that the highlight function is only available for single trait or multiple tracks Manhattan plot, not for multiple traits plot.

**Comment by GuoanQi1996** [comment]
Got it. Thank you for your reply.
