### ISSUE TITLE
How to make background transparent?

### ISSUE THREAD

**Issue by orijitghosh** [YinLiLin/CMplot#30]
Hi,
Is there an option to make the background of the resultant image transparent?
Best,
A

**Comment by YinLiLin** [comment]
Sorry that transparent image is not available at current version.

**Comment by ricebrian** [comment]
I support this comment to have a transparent background

**Comment by YinLiLin** [comment]
Thanks for your suggestion. I will try to achieve it in the next version, and will leave a message here if finished.

**Comment by YinLiLin** [comment]
Hi @ricebrian @orijitghosh,
I want to share the news that the latest version 4.4.0 on Github has the ability of outputting a transparent background image by specifying CMplot(..., file='png').

**Comment by orijitghosh** [comment]
Thank you so much @YinLiLin
