### ISSUE TITLE
Highlight.text overlapping data point

### ISSUE THREAD

**Issue by YannLeGuen** [YinLiLin/CMplot#35]
First thank you for this wonderful tool!

Would it be possible to avoid that the text overlap datapoint of the manhattan plots?

Thanks,
Yann

**Comment by YinLiLin** [comment]
Thanks for using CMplot. I suggest to include this datapoint in your highlighted SNPs and assign NA for it in the corresponding position of text vector

**Comment by YannLeGuen** [comment]
This would be a convenient solution. However it does not work. I should say that I am trying the multracks option (TRUE).
Given the following
```
a <- vector of all SNPs to avoid
b <- vector of SNPs with a true label
a <- a[!(a %in% b)]
c <- vector of labels for b
d <-  rep(c(NA), times=length(a))
SNPs2<- c(b, a)
genes2 <- c(c, d)
genes <- list(genes1, genes2)
SNPs <- list(SNPs1, SNPs2)
```

This produces the following error:
```
 Error in highlight_text(x = pvalue.posN[highlight_index[[i]]], y = logpvalue[highlight_index[[i]]],  : 
  highlighted genes not equal to the highlighted SNPs.
```
Replacing
`d <-  rep(c('G'), times=length(a))`
Leads to no error. However, as expected the other dots are labelled, which is not the behavior I want. 

Thus, NA does not seem to be an acceptable value.

Thanks,
Yann

**Comment by YannLeGuen** [comment]
Maybe it's problem of sorting. I will try that.

**Comment by YannLeGuen** [comment]
Just re-read your post. 
I should assign NA to highlight.text.yadj and .highlight.text.xadj

**Comment by YinLiLin** [comment]
Hi Yann,

Sorry for not replying in time. 
If you only have one trait, just use 'vector' rather than 'list'
taking one trait for an example:
assuming there are 5 SNPs: SNP1, SNP2, SNP3, SNP4, SNP5, and we want to highlight SNP1, SNP3, SNP5 with labels of GENE1, GENE3, and GENE5, but as you encountered, the points of SNP2 and SNP4 are overlapped with the labels of other 3 SNPs, to avoid this matter, you can try as following:
```r
CMplot(..., highlight=c("SNP1","SNP2","SNP3","SNP4","SNP5"), highlight.text=c("GENE1",NA,"GENE3",NA,"GENE5"))
```

LL

**Comment by YannLeGuen** [comment]
I have multiple traits as suggested by the line, where genes1 are the genes for trait1 and genes2 are the genes to highlight for trait2.
```
genes <- list(genes1, genes2)
SNPs <- list(SNPs1, SNPs2)
```
The proposed suggestion does not apply.
