### ISSUE TITLE
Sequence interval visualization

### ISSUE THREAD

**Issue by kaanokay** [YinLiLin/CMplot#38]
Hi,

First, I would like to thank you for this nice package.

I am wondering that can I give a genomic interval coordinate like chr5:565622-565650 instead of an exact genomic coordinate like chr5:565622 to draw the SNP-density plot?

Thanks.
Best wishes.

**Comment by YinLiLin** [comment]
Hi,

Thanks for using CMplot. Sorry that it can not be achieved by CMplot, as the SNP-density plot needs to count the number of SNP in a region, you should provide every single SNPs on entire genome.

Best,
Lilin

**Comment by kaanokay** [comment]
@YinLiLin thanks for your help. I will try another way for that.

Best wishes.
