### ISSUE TITLE
List of values for highlight.pch?

### ISSUE THREAD

**Issue by michaelofrancis** [YinLiLin/CMplot#62]
Hi YinLiLin,

I really enjoy CMplot! I was wondering if there is a list of all the values of highlight.pch? Or some way to know the order of shapes without having to plot them out?

Thanks.

**Comment by YinLiLin** [comment]
Hi, thank you for your question.

The order of shapes in 'highlight.pch' is the same with the order of SNP list in 'highlight', by default, all highlighted SNPs have the same shape, you can assign a vector of different shapes to 'highlight.pch' with equal length to 'highlight', but this function is only available for single trait Manhattan plot.

Best,
LL

**Comment by michaelofrancis** [comment]
Hi, I think my question was misunderstood. I meant for example highlight.pch=1 draws a circle, highlight.pch=2 draws a triangle, etc...

**Comment by YinLiLin** [comment]
it's actually the same with the parameter 'pch' of 'plot()' function in R
