### ISSUE TITLE
Save plot to object

### ISSUE THREAD

**Issue by hatre0** [YinLiLin/CMplot#71]
Hi,

Is it possible to save CMplot to an object? e.g. pheno_plot_1 <- CMplot(...) ; pheno_plot_2 <- CMplot(...)
I'd like to be able to combine multiple CMplots with something like grid.arrange
I've tried file.output=FALSE with file="jpg" and no file parameter and get NULL objects.

Thanks for all your help

**Comment by YinLiLin** [comment]
Sorry i have no idea about that, i guess it may be unachievable for CMplot to save it as an object.
