### ISSUE TITLE
Error in jpeg(paste("Circular-Manhattan.", paste(taxa, collapse = "."),  :    unable to start jpeg() device

### ISSUE THREAD

**Issue by muhammadharoon786** [YinLiLin/CMplot#73]
This is the command, I have used because I have more than one p values associated to traits. 

**CMplot(all_files,type="p",plot.type="c",chr.labels=paste("Chr",c(1:10),sep=""),r=0.4,cir.legend=TRUE, outward=FALSE,cir.legend.col="black",cir.chr.h=1.3,chr.den.col="black",file="jpg", memo="",dpi=300,file.output=TRUE,verbose=TRUE,width=10,height=10)**

But, I am receiving this error (Error in jpeg(paste("Circular-Manhattan.", paste(taxa, collapse = "."), : unable to start jpeg() device). 

Further when I run this command suggested by someone, I receive the output as explained below :
> dev.off()
Error in dev.off() : cannot shut down device 1 (the null device)

NOTE: Rectangular plots are working fine but I am only facing this issue while running the script for circular plots. Please suggsest me some solution. Thanks!

**Comment by hyacz** [comment]
Please check the output of the following command:

```
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
   http/ftp     sockets      libxml        fifo      cledit       iconv
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
        NLS       Rprof     profmem       cairo         ICU long.double
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE
    libcurl
       TRUE
```

Is the value of jpeg TRUE?

**Comment by muhammadharoon786** [comment]
hi, thanks for commenting. The reason has been resolved. Actually, I didn't change the name of columns which was main obstacle to make this graph.  Change the name of columns into trait1, trait2, trait3..... for multiple p values.

**Comment by hyacz** [comment]
OK, @YinLiLin let's consider if there could be a friendlier error message here. 

Thank you for using CMplot, feel free to contact us with any questions. 😄
