### ISSUE TITLE
Circular manhattan plot label trait name

### ISSUE THREAD

**Issue by eightYao2** [YinLiLin/CMplot#91]
Hi YinLiLin and everyone:

I have plotted circular manhattan by using CMplot, and tried to lable trait name on the plot,I have adjusted arguement many times still can't work.If using ```data(pig60K)``` as example. 

```
CMplot(pig60K,type="p",
       plot.type="c",
       r=0.4,
       cir.legend=TRUE,
       outward=FALSE, 
       file="jpg",
       dpi=300,file.output=TRUE,verbose=TRUE,width=15,height=15)
``` 

Nomatter I added ```trait.legend.ncol=3``` , ```cir.legend=TRUE```, it's anything I missing or made a mistake?
Does anybody have any idea how could I achieve this?
Thank you so much in advance.

**Comment by eightYao2** [comment]
Thank you for the prompt reply.Could I confirm one thing is the order of traits is plotted from inside to outside?

**Comment by YinLiLin** [comment]
Yes, that is right.

**Comment by eightYao2** [comment]
Thank you so much!Wish you have a nice day.
