### ISSUE TITLE
Run Q-Q plot cause many time

### ISSUE THREAD

**Issue by DamienTan** [YinLiLin/CMplot#93]
Hi, Lilin
 When I used CMplot to generate a Q-Q plot, it spended a lot of time (more than one day) and did not output the result file. How I should do to fix this problem?
Here is my command:
```
CMplot(d1,plot.type="q",conf.int.col=NULL,box=TRUE,file="jpg",memo="Q-Q plot",dpi=600,file.output=TRUE,verbose=TRUE)
```
and  `d1` 
```
CHR	SNP	BP	P
1	chr1:10439_AC/A	10439	0.8001
1	chr1:12807_C/T	12807	0.4605
1	chr1:13273_G/C	13273	0.5556
1	chr1:13417_C/CGAGA	13417	0.3573
1	chr1:13649_G/C	13649	0.3529
```
Best, 
Damien

**Comment by YinLiLin** [comment]
Hi Damien,

The format of the data you provided is not fully consistent with the requirements of CMplot. The order of columns for the required format should be SNP, CHR, BP, P. Please adjust and have a try again.

Best,
LL

**Comment by DamienTan** [comment]
Hi Lilin,
This problem has been solved following your suggestion. Appreciate your timely help.

Best, 
Damien
